options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: bash
    args:
      - -c
      - |
          # Use a different variable name to avoid confusion with Cloud Build substitutions
          changed_files=$(git diff-tree --no-commit-id --name-only -r $COMMIT_SHA)
          echo "$changed_files"

          folders=$(echo "$changed_files" | cut -d/ -f1 | sort -u)
          echo "Detected folders: $folders"

          for folder in $folders; do
            if [ -f "$folder/main.py" ]; then
              echo "Processing function folder: $folder"

              project_id=$(jq -r .\"$folder\".project_id deploy-config.json)
              function_name=$(jq -r .\"$folder\".function_name deploy-config.json)

              if [[ "$project_id" != "null" && "$function_name" != "null" ]]; then
                echo "Deploying $function_name to $project_id"

                gcloud config set project $project_id
                gcloud functions deploy $function_name \
                  --gen2 \
                  --runtime=python311 \
                  --region=europe-west1 \
                  --source=$folder \
                  --entry-point=$function_name \
                  --trigger-http \
                  --allow-unauthenticated
              else
                echo "❌ Config missing for $folder — skipping"
              fi
            fi
          done

          echo "✅ All functions processed."